services:
  - type: web
    name: abatedouro-indicadores
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: PYTHONPATH
        value: pesagem_app/src
