BEGIN;
ALTER TABLE sku_versoes ADD COLUMN IF NOT EXISTS codigo TEXT;
ALTER TABLE sku_versoes ADD COLUMN IF NOT EXISTS apresentacao TEXT;
ALTER TABLE sku_versoes ADD COLUMN IF NOT EXISTS parametros_json TEXT NOT NULL DEFAULT '{}';
COMMIT;
