BEGIN;
DROP TABLE IF EXISTS op_config_snapshots;
DROP TABLE IF EXISTS roteiro_etapa_insumos;
DROP TABLE IF EXISTS roteiro_etapas;
DROP INDEX IF EXISTS ux_roteiro_versao_ativo;
DROP TABLE IF EXISTS roteiro_versoes;
DROP TABLE IF EXISTS etapas_catalogo;
DROP INDEX IF EXISTS ux_sku_versao_ativa;
DROP TABLE IF EXISTS sku_versoes;
COMMIT;
