"""Catalogo oficial da Biblioteca de Relatorios do PRUMO."""

STATUS_DISPONIVEL = "Disponivel"
STATUS_EVOLUCAO = "Disponivel - requer evolucao"
STATUS_ESTRUTURACAO = "Em estruturacao"
STATUS_DEPENDENCIA = "Dependencia funcional"
STATUS_FUTURO = "Futuro"
STATUS_CONGELADO = "Congelado"


RELATORIOS_OFICIAIS = [
    {
        "id": "financeiro-fluxo-caixa",
        "nome": "Fluxo de Caixa",
        "dominio": "Financeiro",
        "objetivo": "Acompanhar disponibilidade prevista e realizada por vencimento e realizacao.",
        "endpoint": "fluxo_caixa",
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Central de Movimentacoes", "Matriz de Impacto Financeiro"],
        "formatos": ["Tela"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-entradas-caixa",
        "nome": "Entradas de Caixa",
        "dominio": "Financeiro",
        "objetivo": "Listar entradas financeiras registradas na fonte unica.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "entradas-caixa"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Central de Movimentacoes"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-saidas-caixa",
        "nome": "Saidas de Caixa",
        "dominio": "Financeiro",
        "objetivo": "Listar saidas financeiras registradas na fonte unica.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "saidas-caixa"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Central de Movimentacoes"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-contas-pagar",
        "nome": "Contas a Pagar",
        "dominio": "Financeiro",
        "objetivo": "Acompanhar titulos de saida em aberto, vencidos e liquidados.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "contas-pagar"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Liquidacao Financeira"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-contas-receber",
        "nome": "Contas a Receber",
        "dominio": "Financeiro",
        "objetivo": "Acompanhar titulos de entrada em aberto, vencidos e liquidados.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "contas-receber"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Liquidacao Financeira"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-dre-gerencial",
        "nome": "DRE Gerencial",
        "dominio": "Financeiro",
        "objetivo": "Medir desempenho economico por competencia gerencial.",
        "endpoint": "dre_gerencial",
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Plano de Contas Mestre", "Matriz de Impacto Financeiro"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-despesas-categoria",
        "nome": "Despesas por Categoria",
        "dominio": "Financeiro",
        "objetivo": "Consolidar despesas por categoria do Plano de Contas.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "despesas-categoria"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Auditoria Financeira"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-despesas-subcategoria",
        "nome": "Despesas por Subcategoria",
        "dominio": "Financeiro",
        "objetivo": "Detalhar despesas por subcategoria gerencial.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "despesas-subcategoria"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Auditoria Financeira"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-receitas",
        "nome": "Receitas",
        "dominio": "Financeiro",
        "objetivo": "Consolidar receitas registradas pela Central de Movimentacoes.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "receitas"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Central de Movimentacoes"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-aportes",
        "nome": "Aportes",
        "dominio": "Financeiro",
        "objetivo": "Acompanhar aportes que impactam caixa sem compor DRE.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "aportes"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Matriz de Impacto Financeiro"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-evolucao-financeira",
        "nome": "Evolucao Financeira",
        "dominio": "Financeiro",
        "objetivo": "Comparar evolucao financeira ao longo de competencias.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "evolucao-financeira"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Historico financeiro consolidado"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "financeiro-competencia-realizacao",
        "nome": "Competencia x Realizacao",
        "dominio": "Financeiro",
        "objetivo": "Comparar criterio de competencia e efetiva realizacao financeira.",
        "endpoint": "relatorio_financeiro_oficial",
        "route_args": {"slug": "competencia-realizacao"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Fluxo de Caixa"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-op",
        "nome": "Producao por OP",
        "dominio": "Producao",
        "objetivo": "Consultar producao consolidada por ordem de producao.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "producao-por-op"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Ordens de Producao"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-sku",
        "nome": "Producao por SKU",
        "dominio": "Producao",
        "objetivo": "Analisar producao por produto acabado.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "producao-por-sku"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Ordens de Producao"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-fornecedor",
        "nome": "Producao por Fornecedor",
        "dominio": "Producao",
        "objetivo": "Analisar producao e desempenho por fornecedor de aves.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "producao-por-fornecedor"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["OPs encerradas", "Fornecedores"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-periodo",
        "nome": "Producao por Periodo",
        "dominio": "Producao",
        "objetivo": "Acompanhar producao por intervalo de datas.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "producao-por-periodo"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Dashboard"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-rendimento",
        "nome": "Rendimento",
        "dominio": "Producao",
        "objetivo": "Medir rendimento industrial de OPs encerradas.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "rendimento"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Pesagem", "OPs encerradas"],
        "formatos": ["Tela", "Excel", "PDF"],
        "permissao": "pcp",
    },
    {
        "id": "producao-condenacoes",
        "nome": "Condenacoes",
        "dominio": "Producao",
        "objetivo": "Acompanhar condenacoes registradas pela qualidade.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "condenacoes"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Descartes e perdas"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-perdas",
        "nome": "Perdas",
        "dominio": "Producao",
        "objetivo": "Consolidar perdas industriais e descartes.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "perdas"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Qualidade"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-eficiencia",
        "nome": "Eficiencia",
        "dominio": "Producao",
        "objetivo": "Acompanhar produtividade horaria oficial com base em producao, tempos e paradas registrados.",
        "endpoint": "relatorio_producao_oficial",
        "route_args": {"slug": "eficiencia"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_EVOLUCAO,
        "dependencias": ["Tempos por setor", "Paradas por OP", "Meta/capacidade oficial futura para percentual de eficiencia"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "producao-oee",
        "nome": "OEE",
        "dominio": "Producao",
        "objetivo": "Futuro indicador oficial de disponibilidade, performance e qualidade.",
        "endpoint": None,
        "prioridade": "Baixa",
        "onda": "Futuro",
        "status": STATUS_FUTURO,
        "dependencias": ["Motor de OEE ainda nao implantado"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-entradas",
        "nome": "Entradas",
        "dominio": "Almoxarifado",
        "objetivo": "Consultar entradas de insumos no almoxarifado.",
        "endpoint": "relatorio_almoxarifado_oficial",
        "route_args": {"slug": "entradas"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Almoxarifado"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-consumo",
        "nome": "Consumo",
        "dominio": "Almoxarifado",
        "objetivo": "Consultar consumo e saidas de insumos.",
        "endpoint": "relatorio_almoxarifado_oficial",
        "route_args": {"slug": "consumo"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Movimentacoes de Almoxarifado"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-giro",
        "nome": "Giro",
        "dominio": "Almoxarifado",
        "objetivo": "Medir giro de estoque por produto e periodo.",
        "endpoint": None,
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_ESTRUTURACAO,
        "dependencias": ["Historico real de entradas, consumos e lotes no Almoxarifado"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-estoque-atual",
        "nome": "Estoque Atual",
        "dominio": "Almoxarifado",
        "objetivo": "Exibir saldo atual de insumos.",
        "endpoint": "relatorio_almoxarifado_oficial",
        "route_args": {"slug": "estoque-atual"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Saldos de Almoxarifado"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-estoque-local",
        "nome": "Estoque por Local",
        "dominio": "Almoxarifado",
        "objetivo": "Analisar estoque de insumos por local de armazenamento.",
        "endpoint": None,
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_ESTRUTURACAO,
        "dependencias": ["Campo oficial de local/deposito no Almoxarifado"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-estoque-produto",
        "nome": "Estoque por Produto",
        "dominio": "Almoxarifado",
        "objetivo": "Detalhar saldo de estoque por produto/insumo.",
        "endpoint": "relatorio_almoxarifado_oficial",
        "route_args": {"slug": "estoque-por-produto"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Saldos de Almoxarifado"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-fifo",
        "nome": "FIFO",
        "dominio": "Almoxarifado",
        "objetivo": "Auditar consumo por ordem de entrada dos lotes.",
        "endpoint": None,
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_ESTRUTURACAO,
        "dependencias": ["Fluxo real de baixa por lote", "Consumos com lote_id", "Historico verificavel"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "almoxarifado-cmv",
        "nome": "CMV",
        "dominio": "Almoxarifado",
        "objetivo": "Relatorio de custo das mercadorias vendidas, congelado por decisao arquitetural.",
        "endpoint": None,
        "prioridade": "Alta",
        "onda": "Congelado",
        "status": STATUS_CONGELADO,
        "dependencias": ["CMV congelado"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "expedicao-transferencias",
        "nome": "Transferencias",
        "dominio": "Expedicao",
        "objetivo": "Acompanhar romaneios de transferencia entre locais.",
        "endpoint": "relatorio_expedicao_oficial",
        "route_args": {"slug": "transferencias"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Romaneio de Transferencia"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "expedicao-vendas",
        "nome": "Vendas",
        "dominio": "Expedicao",
        "objetivo": "Acompanhar romaneios de venda quando a funcionalidade existir.",
        "endpoint": None,
        "prioridade": "Alta",
        "onda": "Onda 3",
        "status": STATUS_DEPENDENCIA,
        "dependencias": ["Romaneio de Venda"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "expedicao-estoque-camara-fria",
        "nome": "Estoque Camara Fria",
        "dominio": "Expedicao",
        "objetivo": "Exibir saldo de Produto Acabado na Camara Fria LSM.",
        "endpoint": "relatorio_expedicao_oficial",
        "route_args": {"slug": "estoque-camara-fria"},
        "prioridade": "Alta",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Estoque PA por local"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "expedicao-historico-caixa",
        "nome": "Historico por Caixa",
        "dominio": "Expedicao",
        "objetivo": "Consultar movimentacoes e origem de uma caixa de PA.",
        "endpoint": "relatorio_expedicao_oficial",
        "route_args": {"slug": "historico-por-caixa"},
        "prioridade": "Media",
        "onda": "Onda 1",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Rastreabilidade de PA"],
        "formatos": ["Tela", "Impressao"],
        "permissao": "pcp",
    },
    {
        "id": "expedicao-rastreabilidade",
        "nome": "Rastreabilidade",
        "dominio": "Expedicao",
        "objetivo": "Rastrear produto acabado da OP ate estoque e romaneio.",
        "endpoint": None,
        "prioridade": "Alta",
        "onda": "Onda 3",
        "status": STATUS_DEPENDENCIA,
        "dependencias": ["NF", "Cliente", "Romaneio de Venda", "Baixa PA por venda"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
    {
        "id": "gerencial-indicadores",
        "nome": "Indicadores",
        "dominio": "Gerencial",
        "objetivo": "Acompanhar indicadores oficiais consolidados sem criar nova fonte de verdade.",
        "endpoint": "relatorio_gerencial_oficial",
        "route_args": {"slug": "indicadores"},
        "prioridade": "Alta",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["DRE Gerencial", "Fluxo de Caixa", "Relatorios oficiais de Producao, Almoxarifado e Expedicao"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "gerencial-comparativos",
        "nome": "Comparativos",
        "dominio": "Gerencial",
        "objetivo": "Comparar periodo atual com periodo anterior equivalente por indicador oficial.",
        "endpoint": "relatorio_gerencial_oficial",
        "route_args": {"slug": "comparativos"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Indicadores oficiais homologados"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "gerencial-tendencias",
        "nome": "Tendencias",
        "dominio": "Gerencial",
        "objetivo": "Evidenciar direcao historica descritiva sem previsao ou meta inventada.",
        "endpoint": "relatorio_gerencial_oficial",
        "route_args": {"slug": "tendencias"},
        "prioridade": "Media",
        "onda": "Onda 2",
        "status": STATUS_DISPONIVEL,
        "dependencias": ["Indicadores oficiais com serie historica suficiente"],
        "formatos": ["Tela", "Excel"],
        "permissao": "pcp",
    },
    {
        "id": "gerencial-dashboard-executivo",
        "nome": "Dashboard Executivo",
        "dominio": "Gerencial",
        "objetivo": "Centralizar leitura executiva de indicadores do PRUMO.",
        "endpoint": None,
        "prioridade": "Alta",
        "onda": "Onda 3",
        "status": STATUS_ESTRUTURACAO,
        "dependencias": ["Decisao futura de Dashboard Executivo oficial"],
        "formatos": ["Catalogo"],
        "permissao": "pcp",
    },
]
